name: Version Bump and Changelog

on:
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Python Semantic Release - Dry Run
        id: semantic-release-dry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          # Run semantic-release in dry-run mode to capture the version
          NEW_VERSION=$(poetry run semantic-release version --dry-run | grep "New version would be" | awk '{print $5}')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Determined new version would be: $NEW_VERSION"

      - name: Create changelog branch
        run: |
          git checkout -b changelog

      - name: Python Semantic Release - Apply Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Actually apply the version changes and generate changelog
          poetry run semantic-release version

      - name: Push changes to changelog branch
        run: |
          git push -u origin changelog

      - name: Create PR with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Version bump to ${{ env.NEW_VERSION }}" \
            --body "This PR contains:\n- Version bump to ${{ env.NEW_VERSION }}\n- Updated changelog with recent changes\n\nGenerated automatically by semantic-release." \
            --base ${{ github.ref_name }} \
            --head changelog